HTTP/1.0 400 Bad Request
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html> 
  <head>
    <title>400 - Bad Request</title>
  </head> 
  <body>
    <div> 
          <h2 >Sorry. We're not here right now.</h2>
    </div>
  </body> 
</html>